[project]
name = "vimdecrypt"
authors=[{name="Gertjan van Zwieten"}]
version = "2.1.0"
readme = "README.md"
requires-python = ">=3.0"
dependencies = ["blowfish"]

[project.scripts]
vimdecrypt = "vimdecrypt:cli"
