#!/usr/bin/env python3

import sys, vimdecrypt

if len(sys.argv) != 2 and len(sys.argv) != 3:
  sys.exit('usage: vimdecrypt [path] [password (optional)]')

with open(sys.argv[1], 'rb') as f:
  if len(sys.argv) == 3:
    if sys.argv[2] == "-":
      # Decrypt using stdin
      with open(0, 'r') as stdin: # 0 is the filedescriptor for stdin
        print(vimdecrypt.decrypt(f, stdin.read().rstrip()))
    else:
      # Decrypt using passed in password
      print(vimdecrypt.decrypt(f, sys.argv[2]))
  else:
    # Ask for password
    print(vimdecrypt.decrypt(f))
